### EDITED FOR 1.1.3
# LoyaltyPoints config file

# How many Loyalty Points should this plugin give after every time cycle?
increment-per-cycle: 1

#AFK Tracking system setup (1 for yes, 0 for no)
afk-tracking-system: 1

# How long should this time cycle be?
# This is based on when the player logs on.
cycle-time-in-seconds: 600

# How often should the plugin update points?
# In an attempt to save system resources, this plugin is designed to update all points
# at a certain interval. This update timer must be less than or equal to "cycle-time-in-seconds."
# The timer updates points every x seconds since server start.
# I suggest that if you want a fast but accurate point tracker, you should set this timer
# to 60 seconds (every 1 minute), a fourth (cycle-time divided by 4) or a half of the cycle time (cycle-time-in-seconds divided by 2)
update-timer: 150

#
#
# how often should the script save the points, play time and so on (def: 3600 (every 1 hour))
SaveTimer: 3600 

# When a new player logs on, how many Loyalty Points should he/she already have?
starting-points: 0

# In-game chat tag of the plugin
# do NOT use colors in the plugin-tag!
plugin-tag: '[LoyaltyPoints]'

# Supports color codes: &a-f|0-9
# %PLAYERNAME% specifies the player name being checked.
# %POINTS% specifies the amount of Loyalty Points the player has.
# Message sent when checking your own Loyalty Points (fired using /lp)
self-check-message: '&3You have &b%POINTS% &3Loyalty Points.'
# Message sent when checking another player's Loyalty Points (fired using /lp [playername])
# e.g. /lp KasperFranz
check-otherplayer-message: '&3%PLAYERNAME% has &b%POINTS% &3Loyalty Points.'


# 1 if you want to use file based,
# 2 if you want to use sqLite.
# 3 if you want to use mysql.
# default (2)
point-type: 2



#################################
# Only options if you use mysql #
#################################

mysql-host:
mysql-port:       
# mysqls default port is 3306
mysql-user:
mysql-pass:
mysql-database: